### ISSUE TITLE
ISSUE-18: Escribir scripts SQL para crear las tablas

### ISSUE THREAD

**Issue by lugaresdev** [Tri-Angular/SoulPaws#2]
En esta tarea, se requiere la creación de scripts SQL que definirán las estructuras de las tablas necesarias para el backend de gestión de adopciones de mascotas del proyecto "SoulPaws". Estos scripts deben incluir las definiciones de las tablas con sus respectivas columnas, tipos de datos, claves primarias, claves foráneas, índices y cualquier otra restricción necesaria para garantizar la integridad y eficiencia de la base de datos.

**Comment by lugaresdev** [comment]
@dinho-dev No van a ser necesarios los scripts para crear las tablas de la bases de datos lo hacemos a traves de Spring boot con JPA. Dime luego algo cuando leas esto.

**Comment by neodinho** [comment]
> @dinho-dev No van a ser necesarios los scripts para crear las tablas de la bases de datos lo hacemos a traves de Spring boot con JPA. Dime luego algo cuando leas esto.
No van a ser necesarios los scripts para crear las tablas de la base de datos ya que usamos Hibernate, pero pueden ser útiles para pruebas. De esta manera, no será necesario introducir los datos manualmente cada vez.

**Comment by lugaresdev** [comment]
> > @dinho-dev No van a ser necesarios los scripts para crear las tablas de la bases de datos lo hacemos a traves de Spring boot con JPA. Dime luego algo cuando leas esto.
> > No van a ser necesarios los scripts para crear las tablas de la base de datos ya que usamos Hibernate, pero pueden ser útiles para pruebas. De esta manera, no será necesario introducir los datos manualmente cada vez.

Vale me parece bien. Encárgate de hacer la estructura de carpeta para meter los scripts. Voy a crear una Issue para resolver eso en su rama correspondiente.

**Comment by lugaresdev** [comment]
> > > @dinho-dev No van a ser necesarios los scripts para crear las tablas de la bases de datos lo hacemos a traves de Spring boot con JPA. Dime luego algo cuando leas esto.
> > > No van a ser necesarios los scripts para crear las tablas de la base de datos ya que usamos Hibernate, pero pueden ser útiles para pruebas. De esta manera, no será necesario introducir los datos manualmente cada vez.
> 
> Vale me parece bien. Encárgate de hacer la estructura de carpeta para meter los scripts. Voy a crear una Issue para resolver eso en su rama correspondiente.
He creado la issue #18 para resolver lo de la carpetas de los scripts y la rama correspondiente issue-21

**Comment by lugaresdev** [comment]
closes #2 Está resuelto.
